# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myFunction <- function(x) {
    .Call(`_reem_myFunction`, x)
}

simul_C <- function(prms) {
    .Call(`_reem_simul_C`, prms)
}

